### PR TITLE
Changes to support unix build on Mac

### PR DESCRIPTION
**Pull request by plavjanik**
This change allows to build micropython/unix on Mac.

### CODE REVIEW

File: unix/Makefile [hunk 1]
```diff
@@ -61,6 +61,7 @@ endif
 # if necessary override the value of 'CC' set in py/mkenv.mk
 ifeq ($(UNAME_S),Darwin)
 CC = clang
+CFLAGS += -Wno-shift-negative-value
```
Comment (stinos) [inline unix/Makefile]: I don't know where the warning happens, but maybe it can be fixed there?

File: py/makeqstrdefs.py [hunk 2]
```diff
@@ -26,14 +25,15 @@ def write_out(fname, output):
...
 def process_file(f):
     output = []
     last_fname = None
-    outf = None
     for line in f:
         if line and line[0:2] == "# ":
-            comp = line.split()
-            fname = comp[2]
+            # There can be spaces in the filename - e.g. "<command line>" so we use regular expression to parse it:
+            match = re.match('#\s+\d+\s+(?P<fname>"[^"]*").*', line)
```
Comment (stinos) [inline py/makeqstrdefs.py]: If you're using a regex anyway, why not make it match the quotes as well and get rid of the assert below?

File: unix/Makefile (hunk 1 above)
Comment (dpgeorge) [inline unix/Makefile]: Yes, where does this give a warning?

File: py/makeqstrdefs.py [hunk 3]
```diff
@@ -5,7 +5,6 @@
 This script works with Python 2.6, 2.7, 3.3 and 3.4.
 """
 
-import sys
```
Comment (dpgeorge) [inline py/makeqstrdefs.py]: Please don't make unnecessary changes like this.

File: py/mkrules.mk [hunk 4]
```diff
@@ -58,14 +58,14 @@ $(BUILD)/%.pp: %.c
 	$(ECHO) "PreProcess $<"
 	$(Q)$(CC) $(CFLAGS) -E -Wp,-C,-dD,-dI -o $@ $<
 
-# The following rule uses | to create an order only prereuisite. Order only
+# The following rule uses | to create an order only prerequisite. Order only
```
Comment (dpgeorge) [inline py/mkrules.mk]: Please, no changes that are just spelling fixes.

File: unix/Makefile (hunk 1 above)
Comment (plavjanik) [inline unix/Makefile]: This is the error message:

```c
../py/objlist.c:272:78: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
    mp_uint_t index = mp_get_index(self->base.type, self->len, n_args == 1 ? MP_OBJ_NEW_SMALL_INT(-1) : args[1], false);
                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~
../py/obj.h:86:78: note: expanded from macro 'MP_OBJ_NEW_SMALL_INT'
#define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_int_t)(small_int)) << 1) | 1))
                                                     ~~~~~~~~~~~~~~~~~~~~~~~ ^
1 error generated.
```

The other way how to prevent the error on Mac is to cast the `small_int` to unsigned ``mp_uint_t``:
```c
#define MP_OBJ_NEW_SMALL_INT(small_int) ((mp_obj_t)((((mp_uint_t)(small_int)) << 1) | 1))
```
The MP_OBJ_SMALL_INT_VALUE macro converts it back to ``mp_int_t`` correctly.

File: py/makeqstrdefs.py (hunk 2 above)
Comment (plavjanik) [inline py/makeqstrdefs.py]: I have removed the assert for quotes outside of the regex, modified the regex to match just the file name without quotes and added assert to check that there is a match.

File: unix/Makefile (hunk 1 above)
Comment (dpgeorge) [inline unix/Makefile]: I fixed this in 2bddfd492255d03a695a1e7488de3fba80b8e5ab

**Comment by dpgeorge** [comment]
@plavjanik can you please check the latest code from master?  It might now build correctly on Mac with no extra changes.

File: py/mkrules.mk (hunk 4 above)
Comment (pfalcon) [inline py/mkrules.mk]: Typo fixes were committed separately, thanks for pointing them out.

File: unix/Makefile (hunk 1 above)
Comment (plavjanik) [inline unix/Makefile]: Both problems are fixed on master now.

**Comment by plavjanik** [comment]
The latest code on master resolved both problems. Thank you. I am closing the request.
