### PR TITLE
stm32/sdio.c: Fix undefined reference to DMA stream on H7.

### PR DESCRIPTION
**Pull request by iabdalkader**

### CODE REVIEW

**Comment by dpgeorge** [comment]
I assume you tested this on a H7 and it works?

**Comment by iabdalkader** [comment]
> I assume you tested this on a H7 and it works?

No not yet I will test it when I update to Micropython 1.16 later I just noticed this commit randomly, but the changes you introduced in a96afae90f6e5d693173382561d06e583b0b5fa5 only affect F7, so it should still be working. This PR fixes the build on the H7 because as you know SDMMC on H7 use its internal DMA (and doesn't not define dma_SDIO_0).

**Comment by dpgeorge** [comment]
Any updates on testing this PR?

**Comment by iabdalkader** [comment]
Yes it fixes the H7 (with CYW) build which was broken with the changes introduced in https://github.com/micropython/micropython/commit/a96afae90f6e5d693173382561d06e583b0b5fa5 :
```bash
/usr/local/gcc-arm-none-eabi-10-2020-q4-major/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld: /home/mux/src/c/stm32f4/openmv/src/build/micropython/sdio.o: in function `sdio_transfer_cmd53':
sdio.c:(.text.sdio_transfer_cmd53+0x360): undefined reference to `dma_SDIO_0'
collect2: error: ld returned 1 exit status
```

Other than that, these changes have no affect on the H7 because the H7 SDMMC does Not use the dma_nohal API at it all because it uses the internal DMA, but I tested WiFi anyway and it's still working.

**Comment by dpgeorge** [comment]
Yes, you're right.  Merged in f4dce15c87c9ff6c51d8a9a7a80347465468b7af
