### PR TITLE
stmhal/dma.c: Modify dma_init() to accept init params as a struct

### PR DESCRIPTION
**Pull request by blmorris**
This removes hard-coded DMA init params from dma_init(), instead requiring
that the params are ~~set when the dma handle is created.~~ passed as an argument to dma_init()
This allows dma_init to be more generic so it can be used in cases like
I2S and SD Card which require different initialization parameters.

Edited to reflect changes to the commit.

### CODE REVIEW

**Comment by blmorris** [comment]
This commit appears to work correctly, but I am going to keep banging on it to make sure it didn't break SPI or I2C functions. If this looks like the wrong way to solve the problem, I'm happy to accept that ;)
The problem that I'm trying to solve is discussed here: https://github.com/micropython/micropython/commit/3d30d605f5286774edb7669f3958628e5c656048#commitcomment-11771235

**Comment by blmorris** [comment]
Please disregard this PR for now - I mixed up my firmware images and was testing on the master branch. This commit hard-faults on SPI transfers. I will attempt another fix.

**Comment by blmorris** [comment]
This seems to work now - I squashed down to a single commit because the many of the changes in this fix just reversed things from the original PR.
One possible improvement - i2c_dma_init and spi_dma_init are identical, so it may make send to declare a single structure in dma.h and call it spi_i2c_dma_init.

File: stmhal/dma.c [hunk 1]
```diff
@@ -80,7 +80,7 @@ static int get_dma_id(DMA_Stream_TypeDef *dma_stream) {
     }
 }
 
-void dma_init(DMA_HandleTypeDef *dma, DMA_Stream_TypeDef *dma_stream, uint32_t dma_channel, uint32_t direction, void *data) {
+void dma_init(DMA_HandleTypeDef *dma, DMA_Stream_TypeDef *dma_stream, DMA_InitTypeDef dma_init, uint32_t dma_channel, uint32_t direction, void *data) {
```
Comment (dpgeorge) [inline stmhal/dma.c]: It should take a pointer to the DMA_InitTypeDef to avoid copying a large amount of data for the function call.

File: stmhal/dma.c [hunk 2]
```diff
@@ -92,7 +92,9 @@ void dma_init(DMA_HandleTypeDef *dma, DMA_Stream_TypeDef *dma_stream, uint32_t d
 
     // initialise critical parameters
     dma->Instance = dma_stream;
+    dma->Init = dma_init;
```
Comment (dpgeorge) [inline stmhal/dma.c]: With dma_init a pointer this should be `*dma->Init = *dma_init;`

File: stmhal/i2c.c [hunk 3]
```diff
@@ -116,6 +116,16 @@ I2C_HandleTypeDef I2CHandle2 = {.Instance = NULL};
 I2C_HandleTypeDef I2CHandle3 = {.Instance = NULL};
 #endif
 
+// Default DMA parameters to pass to dma_init(); first two params are Channel
+// and Direction which get passed separately.
+// Remaining values in order are PeriphInc, MemInc, PeriphDataAlignment, MemDataAlignment,
+// Mode, Priority, FIFOMode, FIFOThreshold, MemBurst, and PeriphBurst
+STATIC const DMA_InitTypeDef i2c_dma_init = {
```
Comment (dpgeorge) [inline stmhal/i2c.c]: You can use named initialisation to make it clearer: `.PeriphInc = DMA_PINC_DISABLE, .MemInc = ...`.

Comment (dpgeorge) [inline stmhal/i2c.c]: This will also help to prevent bugs if the structure is changed in a new version of the HAL.

**Comment by dpgeorge** [comment]
> One possible improvement - i2c_dma_init and spi_dma_init are identical, so it may make sense to declare a single structure in dma.h and call it spi_i2c_dma_init.

Yes I agree it should be done this way.  Maybe call it `dma_init_struct_spi_i2c`.

**Comment by blmorris** [comment]
Great, thanks for the feedback. All makes sense to me, I'll update the PR tonight.

**Comment by blmorris** [comment]
Updated PR to incorporate suggested changes, but I haven't been able to build or test yet.
Currently the linker is failing with the following error:
```
CC dma.c
CC i2c.c
CC spi.c
LINK build-PYBV10/firmware.elf
build-PYBV10/i2c.o:(.data.dma_init_struct_spi_i2c+0x0): multiple definition of `dma_init_struct_spi_i2c'
build-PYBV10/dma.o:(.data.dma_init_struct_spi_i2c+0x0): first defined here
build-PYBV10/spi.o:(.data.dma_init_struct_spi_i2c+0x0): multiple definition of `dma_init_struct_spi_i2c'
build-PYBV10/dma.o:(.data.dma_init_struct_spi_i2c+0x0): first defined here
make: *** [build-PYBV10/firmware.elf] Error 1
```
I think I know what the problem is (defining a structure in `dma.h` which is then included in `dam.c`, `i2c.c` and `spi.c`) but I'm not sure the best way to resolve it.

**Comment by dpgeorge** [comment]
You need to declare the struct in dma.h using extern and then define it in dma.c.

**Comment by blmorris** [comment]
@dpgeorge - Thanks, I had just figured it out myself and pushed an update, but I somehow thought the dma init struct needed to be defined in either spi.c or i2c.c to avoid a 'variable declared but not used' error.
I put the shared init struct into dma.c as you suggested and it worked. I amended the commit to do it that way.
It's not a perfect match to your feedback - in `dma.c` I needed to use `dma->Init = *dma_init;` instead of `*dma->Init = *dma_init;` to get it to compile; it seems to work, hopefully it's actually correct.

**Comment by dpgeorge** [comment]
> in dma.c I needed to use dma->Init = *dma_init; instead of *dma->Init = *dma_init; to get it to compile; it seems to work, hopefully it's actually correct.

Yes what you did is correct.

**Comment by blmorris** [comment]
> Yes what you did is correct.

Great, thanks. Would it help if I squashed it all down to one commit?

**Comment by dpgeorge** [comment]
You can squash, but I'll probably need to rebase anyway so will do it then, no problems.

**Comment by dpgeorge** [comment]
Merged in c5175526dda06d278dd569dd7bfce0c65cbbe5fc.  Note that I made the dma_init_struct_spi_i2c const so that it's stored in ROM.

**Comment by blmorris** [comment]
> Merged in c517552. Note that I made the dma_init_struct_spi_i2c const so that it's stored in ROM.

Good. I meant to do that but didn't figure out how - I now see that the const keyword is needed in every declaration.
