### PR TITLE
nrf: Add block device for VFS (v2)

### PR DESCRIPTION
**Pull request by dpgeorge**
This is a rebase of #5472 on latest master.

### CODE REVIEW

**Comment by mzdaniel** [comment]
Thank you for looking into this @dpgeorge. 

Compilation works straight now.  Here are some of the issues I found:

1) extmod/vfs_basic.py test is failing (regresion since #5472)

./run-tests.py --clean-failures
./run-tests.py --target nrf extmod/vfs_basic.py
./run-tests.py --print-failures| less

 stat /x OSError
 1 mount False False
 ['test_mnt']
-('test_mnt', 16384, 0)
-StopIteration
-StopIteration
...
+Traceback (most recent call last):
+  File "<stdin>", in <module>
+AttributeError: 'module' object has no attribute 'ilistdir'
+CRASH
\ No newline at end of file

FAILURE /data/micropython/repo/micropython/tests/results/extmod_vfs_basic.py


BTW may I ask for a review of https://github.com/micropython/micropython/pull/6395 ?  tail on the previous output would look as follow

-5 chdir /subdir
-OSError
-/
+Traceback (most recent call last):
+  File "<stdin>", line 90, in <module>
+AttributeError: 'module' object has no attribute 'ilistdir'
+CRASH
\ No newline at end of file

FAILURE /data/micropython/repo/micropython/tests/results/extmod_vfs_basic.py


2) The following code seems to freeze micropython. 

echo "import os; print(os.listdir()); os.mkdir('lib')" > mkdir_test
mpremote run mkdir_test 
[]
(... and at this point micropython freezes)

**Comment by dpgeorge** [comment]
Thanks @mzdaniel for testing.

I have added `uos.ilistdir` to fix point 1.

Point 2 was due to the flash size ioctl reporting bytes rather than blocks, and so littlefs thought the flash was much larger than it really is and so it attempted to read/write out-of-bounds flash.  This is now fixed.

I also tidied up a few other minor things.  So this should now be ready to go in.

**Comment by mzdaniel** [comment]
Sound great! And thank you for your changes Damien.
I'll propose in a new PR changing the FLASH_PAGESIZE default and increasing fs size wherever appropriate.
