### PR TITLE
ci: Prepare to add esp32 to size report.

### PR DESCRIPTION
**Pull request by jepler**
### Summary

I noticed that no xtensa builds were reported in the size report. I also made improvements to the surrounding scripts:
 * metrics.py now uses all available CPU parallelsim for calling "make"
 * metrics.py now cleans mpy-cross if it's used
 * for local testing, the set of PORTS_TO_CHECK, REFERENCE and COMPARISON can be overridden
 * for local testing, the original branch is restored after ci_code_size_build
 * pipefail manipulation is simplified by use of subshells
 * the command to generate the size change report is now a ci.sh step, ci_code_size_report
 * a possible unrelated error due to failure within the pipeline `zcat | tar` will now be caught
 * metrics.py can take a "pre_cmd" for a given port, used to inject the idf shell environment when building that port. A port's pre_cmd can be added or changed by setting an environment variable.

### Testing

I ran various ci.sh steps locally.

### Trade-offs and Alternatives

My past experience with having the idf environment loaded while trying to do other-port building made me believe that the approach I took is preferable to having the idf environment active through all of the size check build.

Due to the fact that the git version of `metrics.py` is used, _it breaks to actually add the build to the size check as part of this PR_, because at the base ref the build fails.

```diff
From fd5bf462c04c4135886d364a624333474fd9e170 Mon Sep 17 00:00:00 2001
From: Jeff Epler <jepler@gmail.com>
Date: Wed, 3 Sep 2025 13:49:55 -0500
Subject: [PATCH] ci: Add esp32 to code size build.

Signed-off-by: Jeff Epler <jepler@gmail.com>
---
 tools/ci.sh | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/tools/ci.sh b/tools/ci.sh
index 5417ce8797..bfd1aaf357 100755
--- a/tools/ci.sh
+++ b/tools/ci.sh
@@ -75,11 +75,12 @@ function ci_code_size_setup {
     ci_gcc_arm_setup
     ci_gcc_riscv_setup
     ci_picotool_setup
+    ci_esp32_idf_setup
 }
 
 function ci_code_size_build {
     # check the following ports for the change in their code size
-    PORTS_TO_CHECK=${1-bmusxpdv}
+    PORTS_TO_CHECK=${1-bmusxpdv3}
     SUBMODULES="lib/asf4 lib/berkeley-db-1.xx lib/btstack lib/cyw43-driver lib/lwip lib/mbedtls lib/micropython-lib lib/nxp_driver lib/pico-sdk lib/stm32lib lib/tinyusb"
 
     # Default GitHub pull request sets HEAD to a generated merge commit
-- 
2.47.2

```

### CODE REVIEW

**Comment by Josverl** [comment]
I have been wondering about the missing esp32 port in the size reports.
Thanks for this.

File: tools/ci.sh [hunk 1]
```diff
@@ -93,33 +93,38 @@ function ci_code_size_build {
...
+            tools/metrics.py clean "$PORTS_TO_CHECK"
+            # Allow errors from tools/metrics.py to propagate out of the pipe below.
+            set -o pipefail
+            tools/metrics.py build "$PORTS_TO_CHECK" | tee $OUTFILE
+        }
 
-    set +o pipefail
-    unset -f code_size_build_step
+        # build reference, save to size0
+        # ignore any errors with this build, in case master is failing
```
Comment (dpgeorge) [inline tools/ci.sh:127]: Is this comment still true, are errors in the REFERENCE build still ignored?

File: tools/ci.sh [hunk 2]
```diff
@@ -93,33 +93,38 @@ function ci_code_size_build {
...
+        code_size_build_step $REFERENCE ~/size0
+        # build PR/branch, save to size1
+        code_size_build_step $COMPARISON ~/size1
```
Comment (dpgeorge) [inline tools/ci.sh]: Is the return value of this last step propagated out as the return value / result of the entire `ci_code_size_build` function?

File: tools/ci.sh [hunk 3]
```diff
@@ -93,33 +93,38 @@ function ci_code_size_build {
...
+    )
+}
 
-    return $STATUS
+function ci_code_size_report {
+    # Allow errors from tools/metrics.py to propagate out of the pipe above.
```
Comment (dpgeorge) [inline tools/ci.sh:135]: above -> below?

File: tools/metrics.py [hunk 4]
```diff
@@ -65,7 +66,12 @@ def __init__(self, name, dir, output, make_flags=None):
     "s": PortData("stm32", "stm32", "build-PYBV10/firmware.elf", "BOARD=PYBV10"),
     "c": PortData("cc3200", "cc3200", "build/WIPY/release/application.axf", "BTARGET=application"),
     "8": PortData("esp8266", "esp8266", "build-ESP8266_GENERIC/firmware.elf"),
-    "3": PortData("esp32", "esp32", "build-ESP32_GENERIC/micropython.elf"),
+    "3": PortData(
+        "esp32",
+        "esp32",
+        "build-ESP32_GENERIC/micropython.elf",
+        pre_make_cmd=[".", "esp-idf/export.sh"],
```
Comment (dpgeorge) [inline tools/metrics.py]: It feels like this should be configurable by a command-line option, or environment variable.  (Eg for myself I have a shell alias `idf` which gets me the correct IDF environment.)

File: tools/metrics.py [hunk 5]
```diff
@@ -75,14 +81,22 @@ def __init__(self, name, dir, output, make_flags=None):
 }
 
 
-def syscmd(*args):
+def quoted(args):
+    return " ".join(shlex.quote(word) for word in args)
+
+
+def syscmd(*args, pre_make_cmd=None):
```
Comment (dpgeorge) [inline tools/metrics.py]: Maybe it can be just `pre_cmd`, because this `syscmd` function can be used for more than just running make (in principle).

**Comment by dpgeorge** [comment]
The main reason to not include esp32 in the size report is that it takes a long time to build, and the code-size-report step is already one of the slowest CI jobs.

Nevertheless, code size reports have proved very useful (to me at least), so probably it's a good idea to add esp32 as well.

File: tools/ci.sh (hunk 1 above)
Comment (jepler) [reply tools/ci.sh:127]: no, this was changed in 4c55b0879b38b373b44e84552d6754b7842b5b72 but the comment was not removed.

I _think_ that adding pipefail is the "real fix" and removing $IGNORE_ERRORS was not needed.

Would you like me to restore $IGNORE_ERRORS or remove the outdated comment?

File: tools/ci.sh (hunk 2 above)
Comment (jepler) [reply tools/ci.sh]: We're running in `set -e` so any individual nonzero exit status not otherwise handled makes the whole thing exit. So if build_step fails (whether for REFERENCE or COMPARISON) the whole job fails.

In my local WIP I've restored $IGNORE_ERRORS, which means that a failure at REFERENCE results in success (zero exit status), while a failure at COMPARISON results in success (nonzero exit status)

```
(micropython) jepler@bert:~/src/micropython$ PORTS_TO_CHECK=bm REFERENCE=HEAD COMPARISON=broken-minimal bash -x ./tools/ci.sh code_size_build > /dev/null 2>&1 ; echo $?
1
(micropython) jepler@bert:~/src/micropython$ PORTS_TO_CHECK=bm REFERENCE=broken-minimal COMPARISON=HEAD bash -x ./tools/ci.sh code_size_build > /dev/null 2>&1 ; echo $?
0
```

File: tools/metrics.py (hunk 4 above)
Comment (jepler) [reply tools/metrics.py]: In my WIP I've implemented it so that an environment variable such as `PRE_CMD_b=fnord` will supply a different PRE_CMD for the build tagged with 'b'.

File: tools/metrics.py (hunk 5 above)
Comment (jepler) [reply tools/metrics.py]: OK

File: tools/metrics.py (hunk 4 above)
Comment (jepler) [reply tools/metrics.py]: now pushed.

File: .github/workflows/code_size.yml [hunk 6]
```diff
@@ -33,7 +33,7 @@ jobs:
     - name: Build
       run: source tools/ci.sh && ci_code_size_build
     - name: Compute code size difference
-      run: tools/metrics.py diff ~/size0 ~/size1 | tee diff
+      run: source tools/ci.sh && ci_code_size_report
```
Comment (jepler) [inline .github/workflows/code_size.yml:36]: should the CI scripts be changed to use the `tools/ci.sh code_size_report` style instead (as a separate PR)?

File: tools/ci.sh (hunk 1 above)
Comment (jepler) [reply tools/ci.sh:127]: I restored it, and tested that REFERENCE failures don't fail the overall script but COMPARISON failures do. This was "easy" since I could use a broken ref for REFERENCE or COMPARISON via environment settings.

File: tools/ci.sh [hunk 7]
```diff
@@ -82,47 +82,58 @@ function ci_code_size_setup {
 
 function ci_code_size_build {
     # check the following ports for the change in their code size
-    PORTS_TO_CHECK=bmusxpdv
+    # Override the list by setting PORTS_TO_CHECK in the environment before invoking ci.
+    : ${PORTS_TO_CHECK:=bmusxpdv}
+    
     SUBMODULES="lib/asf4 lib/berkeley-db-1.xx lib/btstack lib/cyw43-driver lib/lwip lib/mbedtls lib/micropython-lib lib/nxp_driver lib/pico-sdk lib/stm32lib lib/tinyusb"
```
Comment (jepler) [inline tools/ci.sh:88]: should this be moved into the metrics script, like `metrics.py submodule  "$PORTS_TO_CHECK"`? (which would "make submodules" in each location called for)

File: .github/workflows/code_size.yml (hunk 6 above)
Comment (projectgus) [reply .github/workflows/code_size.yml:36]: Seems like a reasonable cleanup to me

**Review by projectgus — APPROVED** [review]
This change looks good to me, thanks @jepler!

Regarding performance, we have some caching steps in `ports_esp32.yml` ("Cached ESP-IDF install" and "ccache") that could be worth bringing into the code_size GitHub workflow as well to save build time (I'm not sure if there's a good way we can reuse them, or if copy/paste is the only way.)

(If we wanted to really speed code_size calculation up, then I think we could use the "GitHub Artifacts" feature to temporarily store the build directories from the other build jobs and then copy all their contents into the code_size job's working directory before it runs. If we then had a flag to let `metrics.py` do partial builds rather than clean ones then it'd be very fast to complete. But this is still probably a non-trivial amount of messing around.)

File: tools/ci.sh (hunk 1 above)
Comment (dpgeorge) [reply tools/ci.sh:127]: OK, thanks.

**Comment by dpgeorge** [comment]
Rebased and merged in fef414eca49c44180fba9a0ab32e647c0373e67f through 13d49751f4f656c4ea12f3ed4cde2c404cf557ae

**Comment by dpgeorge** [comment]
@jepler looks like this broke esp8266 and esp32 CI.

Eg https://github.com/micropython/micropython/actions/runs/18334237816/job/52215159813 :
```
36850K .......... .......... .......... .......... .......... 99%  331M 0s
 36900K .......... .......... .......... .......... .......... 99%  328M 0s
 36950K .......... .......... ....                            100%  427M=1.4s

2025-10-08 04:57:04 (25.1 MB/s) - ‘xtensa-lx106-elf-standalone.tar.gz’ saved [37861992/37861992]

tools/ci.sh: line 244: set: pipefile: invalid option name
Error: Process completed with exit code 2.
```

and https://github.com/micropython/micropython/actions/runs/18334237807/job/52215159752 :
```
WARNING: Cannot load idf.py extension "component_manager_ext"
Executing action: all (aliases: build)
Running cmake in directory /home/runner/work/micropython/micropython/ports/esp32/build-ESP32_GENERIC_S3
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DPYTHON=/home/runner/.espressif/python_env/idf5.4_py3.12_env/bin/python -DESP_PLATFORM=1 -DMICROPY_BOARD=ESP32_GENERIC_S3 -DMICROPY_BOARD_DIR=/home/runner/work/micropython/micropython/ports/esp32/boards/ESP32_GENERIC_S3 -DCCACHE_ENABLE=1 /home/runner/work/micropython/micropython/ports/esp32"...
-- Found Git: /usr/bin/git (found version "2.51.0")
-- ccache will be used for faster recompilation
-- The C compiler identification is GNU 14.2.0
-- The CXX compiler identification is GNU 14.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/runner/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/bin/xtensa-esp32s3-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/runner/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/bin/xtensa-esp32s3-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/runner/.espressif/tools/xtensa-esp-elf/esp-14.2.0_20241119/xtensa-esp-elf/bin/xtensa-esp32s3-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32s3
CMake Error at /home/runner/work/micropython/micropython/esp-idf/tools/cmake/build.cmake:620 (message):
  Traceback (most recent call last):

    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/home/runner/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/idf_component_manager/prepare_components/__main__.py", line 6, in <module>
      main()
    File "/home/runner/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/idf_component_manager/prepare_components/prepare.py", line 88, in main
      setup_logging()
    File "/home/runner/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/idf_component_tools/logging.py", line 106, in setup_logging
      if ComponentManagerSettings().DEBUG_MODE:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/pydantic_settings/main.py", line 193, in __init__
      super().__init__(
    File "/home/runner/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/pydantic/main.py", line 250, in __init__
      validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/idf_component_tools/environment.py", line 296, in fallback_to_default
      if field.validation_alias:
         ^^^^^^^^^^^^^^^^^^^^^^

  AttributeError: 'NoneType' object has no attribute 'validation_alias'

Call Stack (most recent call first):
  /home/runner/work/micropython/micropython/esp-idf/tools/cmake/project.cmake:718 (idf_build_process)
  CMakeLists.txt:68 (project)

```

**Comment by projectgus** [comment]
It's a typo. `s/pipefile/pipefail/`. One sec, will submit a PR.

**Comment by projectgus** [comment]
I don't know what's going on with the second one, though...

**Comment by projectgus** [comment]
The esp32 thing seems to be a broken package update from Espressif, not antyhing we've changed. Have linked the IDF issue from #18225.

**Comment by jepler** [comment]
Thanks for fixing that typo. How did the ci on this PR turn up green, though?

**Comment by dpgeorge** [comment]
> How did the ci on this PR turn up green, though?

The esp8266 setup actually failed for this PR!  See:
```
36850K .......... .......... .......... .......... .......... 99%  317M 0s
 36900K .......... .......... .......... .......... .......... 99%  313M 0s
 36950K .......... .......... ....                            100%  471M=1.6s

2025-09-28 02:43:07 (23.0 MB/s) - ‘xtensa-lx106-elf-standalone.tar.gz’ saved [37861992/37861992]

tools/ci.sh: line 244: set: pipefile: invalid option name
```
But this didn't propagate out as an error to the GitHub Action.

Except after rebasing on effb9503ebbf7552cec1bc788850f27076cbc132 (I guess) it did turn into an error.

Then the question becomes, how did this PR succeed to build the esp8266 port even though the xtensa gcc wasn't installed???

**Comment by projectgus** [comment]
> Then the question becomes, how did this PR succeed to build the esp8266 port even though the xtensa gcc wasn't installed???

`(set -o pipefile; zcat xtensa-lx106-elf-standalone.tar.gz | tar x)`

Without `set -e`, the first statement fails and prints the error but the next statement runs anyway and the subshell succeeds.

Rebasing on effb950 means this function is called via `_ci_main` which does `set -e` (which is inherited by the subshell), so it stops after the first failed statement. (Evidence that it's a good change to have made!)

Isn't bash *fun*? :laughing:

**Comment by dpgeorge** [comment]
> Without `set -e`, the first statement fails and prints the error but the next statement runs anyway and the subshell succeeds.

Ah, of course!  There's no `&&` here it's `;` instead.

> Isn't bash _fun_?

Fun type 2!
