### PR TITLE
rp2: Fix build failure if threads are disabled.

### LINKED ISSUE #16720: rp2: new mp_thread_recursive_mutex_t code breaks with MICROPY_PY_THREAD disabled
### Port, board and/or hardware

rp2

### MicroPython version

N/A (Build from master)

### Reproduction

This change breaks builds with threading disabled, since `mp_thread_recursive_mutex_t ` is never defined for `pendsv.c`:

https://github.com/micropython/micropython/commit/3bfedd0f4a9e8b11ff97851615ec4761663b0e94

To reproduce, build any rp2 board with `#define MICROPY_PY_THREAD                       (0)`

### Expected behaviour

_No response_

### Observed behaviour

```
micropython/ports/rp2/pendsv.c:50:8: error: unknown type name 'mp_thread_recursive_mutex_t'
   50 | static mp_thread_recursive_mutex_t pendsv_mutex;
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Additional Information

No, I've provided everything above.

### Code of Conduct

Yes, I agree

### PR DESCRIPTION
**Pull request by projectgus**
### Summary

Regression in 3af006efb39ad0b7aa7c0401c93329b654bca617 meant that pendsv.c no longer compiled if threads were disabled in the build config. Add an implementation based on the earlier one (simple counter) for the non-threads case.

To add CI coverage for future breakage of this kind, Damien suggested building one of the boards in CI with threads disabled. To support this, I've added support for the `CFLAGS_EXTRA` environment variable in CMake-based ports, similar to other ports (with caveat that it only applies to clean builds).

Closes #16720

*This work was funded through GitHub Sponsors.*

### Testing

* Built `RPI_PICO` default config before and after this change, disassembled with `arm-none-eabi-objdump -d`, and diffed the output to confirm no binary changes.
* Built `RPI_PICO` with `MICROPY_PY_THREAD` defined to 0, confirmed unit tests all pass (except for threads tests).
* Pushed a temporary commit d78f558 to check that the rp2 CI build is applying the config correctly. ([Confirmed](https://github.com/micropython/micropython/actions/runs/13257398311/job/37006503860?pr=16733))

### Trade-offs and Alternatives

* I originally implemented the new counter using atomic increment/decrement, but looking at the usage patterns I couldn't see a reason for this if there's no contention from the second core or multiple threads. Any interrupt handler should exit with the counter at the same value that it was when entering.
* Feels kind of hacky to be making a custom config just for CI, but there's no boards in MicroPython that depend on not having thread support.

### CODE REVIEW

**Comment by projectgus** [comment]
@Gadgetoid Are you folks in a position to do any testing of this fix?

**Comment by Gadgetoid** [comment]
Oooh! Thank you, will test ASAP!

File: ports/rp2/pendsv.c [hunk 1]
```diff
@@ -62,7 +66,41 @@ void pendsv_suspend(void) {
...
+static inline int pendsv_suspend_count(void) {
+    return pendsv_mutex.mutex.enter_count;
+}
+
+#else
+
+// Without threads we don't include any pico-sdk mutex in the build,
+// but also we don't need to worry about cross-thread contention (or
+// races with interrupts that update this counter).
+static int pendsv_counter;
```
Comment (dpgeorge) [inline ports/rp2/pendsv.c:81]: This was originally called `pendsv_lock`... is it more self-documenting to use that name again?

File: ports/rp2/pendsv.c [hunk 2]
```diff
@@ -62,7 +66,41 @@ void pendsv_suspend(void) {
...
+
+void pendsv_init(void) {
+
```
Comment (dpgeorge) [inline ports/rp2/pendsv.c:84]: Please remove blank line here.

File: ports/rp2/pendsv.c [hunk 3]
```diff
@@ -62,7 +66,41 @@ void pendsv_suspend(void) {
...
+}
+
+void pendsv_suspend(void) {
+    pendsv_counter += 1;
```
Comment (dpgeorge) [inline ports/rp2/pendsv.c:88]: I suggest using `++` to match the `--` used below.

File: ports/rp2/pendsv.c [hunk 4]
```diff
@@ -76,7 +114,7 @@ void pendsv_resume(void) {
 
 void pendsv_schedule_dispatch(size_t slot, pendsv_dispatch_t f) {
     pendsv_dispatch_table[slot] = f;
-    if (pendsv_mutex.mutex.enter_count == 0) {
+    if (pendsv_suspend_count() == 0) {
```
Comment (dpgeorge) [inline ports/rp2/pendsv.c:117]: Maybe call it `pendsv_lock_count`?

File: ports/rp2/pendsv.c [hunk 5]
```diff
@@ -97,13 +135,19 @@ void pendsv_schedule_dispatch(size_t slot, pendsv_dispatch_t f) {
...
     if (!mp_thread_recursive_mutex_lock(&pendsv_mutex, 0)) {
         // Failure here means core 1 holds pendsv_mutex. ISR will
         // run again after core 1 calls pendsv_resume().
         return;
     }
     // Core 0 should not already have locked pendsv_mutex
     assert(pendsv_mutex.mutex.enter_count == 1);
+    #else
+    if (pendsv_suspend_count() > 0) {
+        return; // Will run again after pendsv_resume()
```
Comment (dpgeorge) [inline ports/rp2/pendsv.c:148]: The original implementation simply had `assert(pendsv_lock == 0)` here, which is much stricter.  Did you find cases where this handler can be called with `pendsv_lock > 0` ?

**Review by dpgeorge — COMMENTED** [review]
I checked this against 3af006efb39ad0b7aa7c0401c93329b654bca617 and (apart from my comments) it effectively reverts that commit, which is what we want.

File: ports/rp2/pendsv.c (hunk 4 above)
Comment (projectgus) [reply ports/rp2/pendsv.c:117]: This function returns the count of times `pendsv_suspend()` has been called, but I can change the name if you prefer.

File: ports/rp2/pendsv.c (hunk 5 above)
Comment (projectgus) [reply ports/rp2/pendsv.c:148]: Probably not on single threaded, assuming the PendSV runs without latency. Will change back to the assert.

File: ports/rp2/pendsv.c (hunk 4 above)
Comment (dpgeorge) [reply ports/rp2/pendsv.c]: Oh, right.  Keep it as `pendsv_suspend_count()`.

**Review by dpgeorge — APPROVED** [review]

**Comment by dpgeorge** [comment]
@Gadgetoid did you want to test this fix?  It looks good to me, but maybe worth testing with your build setup.

**Comment by Gadgetoid** [comment]
Sorry I fell down a rabbit hole of distractions! I'll give it a shot now.

**Comment by dpgeorge** [comment]
Thanks @Gadgetoid for testing!
