### PR TITLE
seeed_xiao_esp32c5 support (IDF v5.5)

### PR DESCRIPTION
**Pull request by AZKKXL**
### Summary
The is esp32c5 officially supported in IDF v5.5 
Pulling together changes and generic board support needed here.

### Some details

1. I2S is not enabled: **#define MICROPY_PY_MACHINE_I2S (0)**
2. As of the release/v5.5 version of ESP-IDF, there is only one configuration option for XTAL_FREQ, which is XTAL_FREQ_AUTO. This causes configuration options like CONFIG_XTAL_FREQ_40 added in sdkconfig to not take effect. I have made simple modifications in the source code, which can be adjusted once ESP-IDF opens up the configuration options in the future.
3. Reference links:https://github.com/micropython/micropython/issues/17903 and https://github.com/espressif/esp-idf/issues/17426

### Tesing

- machine.pin

- machine.i2c

- machine.adc

- machine.pwm

- machine.timer

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the contribution.

Please can you separate the changes here into two commits:
- adding C5 support
- adding the new board

**Comment by AZKKXL** [comment]
@dpgeorge 
Thank you for your reply. It has now been revised.

**Comment by Vincent1-python** [comment]
@AZKKXL https://github.com/micropython/micropython/pull/17971/ When this PR ends, this automatic reading problem may be avoided, and he will not ask for XTAL frequency at compile time.

**Comment by AZKKXL** [comment]
@Vincent1-python WOW! That's cool!

File: ports/esp32/boards/SEEED_XIAO_ESP32C5/board.json [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+        "flash_offset": "0x2000"
+    },
+    "docs": "",
+    "features": [
+        "BLE",
+        "External Flash",
+        "WiFi"
+    ],
+    "images": [
+        "esp32c5_devkitmini.jpg"
```
Comment (projectgus) [inline ports/esp32/boards/SEEED_XIAO_ESP32C5/board.json:15]: Is there a PR for this in https://github.com/micropython/micropython-media ?

File: ports/esp32/boards/SEEED_XIAO_ESP32C5/mpconfigboard.h [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// This configuration is for a generic ESP32C2 board with 4MiB (or more) of flash.
```
Comment (projectgus) [inline ports/esp32/boards/SEEED_XIAO_ESP32C5/mpconfigboard.h]:
```suggestion
// This configuration is for a generic ESP32C5 board with 4MiB (or more) of flash.
```

File: ports/esp32/boards/SEEED_XIAO_ESP32C5/mpconfigboard.h [hunk 3]
```diff
@@ -0,0 +1,7 @@
...
+
+#define MICROPY_HW_BOARD_NAME               "ESP32C5 module"
```
Comment (projectgus) [inline ports/esp32/boards/SEEED_XIAO_ESP32C5/mpconfigboard.h:3]:
```suggestion
#define MICROPY_HW_BOARD_NAME               "SEEED XIAO ESP32C5"
```

File: ports/esp32/machine_i2c.c [hunk 4]
```diff
@@ -38,6 +38,12 @@
 #if SOC_I2C_SUPPORT_XTAL
 #if CONFIG_XTAL_FREQ > 0
 #define I2C_SCLK_FREQ (CONFIG_XTAL_FREQ * 1000000)
+#elif CONFIG_XTAL_FREQ == 0 && CONFIG_IDF_TARGET_ESP32C5    // In the official configuration of ESP32C5, there is currently only the AUTO option available.
+                                                            // This causes CONFIG_XTAL_FREQ to be set to 0, resulting in compilation errors.
+                                                            // For now, we'll set it to 40M, and we'll add a configuration item for it later if they open up the configuration interface.
+                                                            // Detailed information: https://github.com/micropython/micropython/issues/17903
+#define CONFIG_XTAL_FREQ 40                                 // If your external crystal frequency is 48, please change this 40 to 48 and recompile.
```
Comment (projectgus) [inline ports/esp32/machine_i2c.c]: Better we merge #17971 first and then rebase to not need this any more. :grinning:

**Review by projectgus — COMMENTED** [review]
Couple of minor suggestions, but this PR looks mostly good to me.

Although it would be good to have a `ESP32_GENERIC_C5` board as well as the SEEED board.

Note we currently do all nightly builds with IDF v5.4.2, so we won't be able to start building ESP32-C5 in nightly builds (or CI) until we bump that version. (Same applies for ESP32-P4 support, I think).

**Comment by AZKKXL** [comment]
@projectgus OK,I resolved conversation : )

**Comment by AZKKXL** [comment]
@projectgus Hello,should the directory "SEEED_XIAO_ESP32C5" be renamed to "ESP32_GENERIC_C5"?

File: ports/esp32/boards/ESP32_GENERIC_C5/mpconfigboard.h [hunk 5]
```diff
@@ -0,0 +1,7 @@
+// This configuration is for a generic ESP32C5 board with 4MiB (or more) of flash.
+
+#define MICROPY_HW_BOARD_NAME               "SEEED XIAO ESP32C5"
```
Comment (projectgus) [inline ports/esp32/boards/ESP32_GENERIC_C5/mpconfigboard.h]: If the board is `ESP32_GENERIC_C5` then this name should be "Generic ESP32C5 Module"

File: ports/esp32/boards/ESP32_GENERIC_C5/pin.csv [hunk 6]
```diff
@@ -0,0 +1,11 @@
...
+D1,GPIO0
+D2,GPIO25
+D3,GPIO7
+D4,GPIO23
+D5,GPIO24
+D6,GPIO11
+D7,GPIO12
+D8,GPIO8
+D9,GPIO9
+D10,GPIO10
```
Comment (projectgus) [inline ports/esp32/boards/ESP32_GENERIC_C5/pin.csv]: This pin.csv file only makes sense for the XIAO board (the ESP32C5 has more GPIOs than this, and doesn't use D0,D1,D2,etc numbering).

For the generic board, remove this file.

**Review by projectgus — COMMENTED** [review]
I see you've changed the XIAO board to `ESP32_GENERIC_C5`, but some additional changes are needed to add this as a generic board.

I have a C5 Devkit on order, so I can help test this PR when it arrives.

**Comment by robert-hh** [comment]
Compiled with a no-name ESP3C5 board using esp-idf v5.5.1. At first, the firmware was too large for the factory partition, ~32k overflow.  SO I added the line below to sdkconfig.board, which reduces the firmware size by about 90k. The line does not have any impact on performance.

`CONFIG_COMPILER_OPTIMIZATION_CHECKS_SILENT=y`

**Comment by dpgeorge** [comment]
@AZKKXL the esp32 port now uses IDF v5.5.1, so this C5 support should work.

Can you please rebase this on latest master?

**Comment by AZKKXL** [comment]
> @AZKKXL the esp32 port now uses IDF v5.5.1, so this C5 support should work.
> 
> Can you please rebase this on latest master?

Already rebase.

**Comment by projectgus** [comment]
@AZKKXL Something went wrong when you rebased (it had 255 commits showing in the PR). I've rebased again and squashed down to one commit so we can re-review.

If you need to make any more local changes then you'll need to reset your local branch to match this remote branch, first. (To do this, run `git fetch origin` and then `git reset --hard origin/seeed_xiao_esp32c5` - but you will lose any other local changes you have in the branch!!)

File: ports/esp32/machine_adc.c [hunk 7]
```diff
@@ -108,6 +108,13 @@ static const machine_adc_obj_t madc_obj[] = {
     {{&machine_adc_type}, ADCBLOCK1, ADC_CHANNEL_4, GPIO_NUM_4},
     {{&machine_adc_type}, ADCBLOCK1, ADC_CHANNEL_5, GPIO_NUM_5},
     {{&machine_adc_type}, ADCBLOCK1, ADC_CHANNEL_6, GPIO_NUM_6},
+    #elif CONFIG_IDF_TARGET_ESP32C5
```
Comment (dpgeorge) [inline ports/esp32/machine_adc.c]: Suggest putting this between C3 and C6 for a sorted ordering.

File: ports/esp32/machine_pin.c [hunk 8]
```diff
@@ -152,7 +152,7 @@ static mp_obj_t machine_pin_obj_init_helper(const machine_pin_obj_t *self, size_
     // reset the pin to digital if this is a mode-setting init (grab it back from ADC)
     if (args[ARG_mode].u_obj != mp_const_none) {
         if (rtc_gpio_is_valid_gpio(index)) {
-            #if !(CONFIG_IDF_TARGET_ESP32C2 || CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C6)
+            #if !(CONFIG_IDF_TARGET_ESP32C2 || CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C6 || CONFIG_IDF_TARGET_ESP32C5)
```
Comment (dpgeorge) [inline ports/esp32/machine_pin.c]: Suggest putting this in sorted order.

File: ports/esp32/machine_pin.c [hunk 9]
```diff
@@ -168,6 +168,11 @@ static mp_obj_t machine_pin_obj_init_helper(const machine_pin_obj_t *self, size_
         CLEAR_PERI_REG_MASK(USB_SERIAL_JTAG_CONF0_REG, USB_SERIAL_JTAG_USB_PAD_ENABLE);
     }
     #endif
+    #if CONFIG_IDF_TARGET_ESP32C5 && !MICROPY_HW_ESP_USB_SERIAL_JTAG
```
Comment (dpgeorge) [inline ports/esp32/machine_pin.c]: Suggest sorted ordering.

File: ports/esp32/machine_pin.h [hunk 10]
```diff
@@ -141,6 +141,32 @@
 #define MICROPY_HW_ENABLE_GPIO23 (1)
 // GPIO 24-30 are used for spi/sip flash.
 
+#elif CONFIG_IDF_TARGET_ESP32C5
```
Comment (dpgeorge) [inline ports/esp32/machine_pin.h]: Suggest putting this new block between the existing C3 and C6 blocks to keep it sorted on SoC.

File: ports/esp32/mpconfigport.h [hunk 11]
```diff
@@ -174,6 +174,8 @@
 #define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "mpy-esp32c3"
 #elif CONFIG_IDF_TARGET_ESP32C6
 #define MICROPY_PY_NETWORK_HOSTNAME_DEFAULT "mpy-esp32c6"
+#elif CONFIG_IDF_TARGET_ESP32C5
```
Comment (dpgeorge) [inline ports/esp32/mpconfigport.h:175]: Sorted ordering.

**Review by projectgus — COMMENTED** [review]
@AZKKXL Looks like this PR only needs some minor cleanup and we can merge it.

**Comment by AZKKXL** [comment]
> n

I apologize for only seeing this now due to personal reasons. Could you confirm if the current submission format is correct? If not, please let me know. I will pay close attention to this in the coming days and strive to complete this PR.

File: ports/esp32/machine_pin.c (hunk 8 above)
Comment (dpgeorge) [reply ports/esp32/machine_pin.c]: This still needs updating to:
```c

            #if !(CONFIG_IDF_TARGET_ESP32C2 || CONFIG_IDF_TARGET_ESP32C3 || CONFIG_IDF_TARGET_ESP32C5 || CONFIG_IDF_TARGET_ESP32C6)
```
(swap C6 and C5 config macros)

**Comment by dpgeorge** [comment]
I tested building the new ESP32_GENERIC_C5 board, and it doesn't build due to two reasons:
- error with redefinition of CONFIG_XTAL_FREQ
- firmware is too big to fit in flash

For the first problem, I suggest dynamically calculating the I2C bus frequency using (in `machine_i2c.c`):
```diff
@@ -263,7 +263,13 @@ static void machine_hw_i2c_init(machine_hw_i2c_obj_t *self, bool first_init) {
         .master.clk_speed = self->freq,
     };
     i2c_param_config(self->port, &conf);
-    int timeout = i2c_ll_calculate_timeout_us_to_reg_val(I2C_SCLK_FREQ, self->timeout_us);
+    #if CONFIG_IDF_TARGET_ESP32C5
+    uint32_t i2c_sclk_freq;
+    check_esp_err(esp_clk_tree_src_get_freq_hz(I2C_CLK_SRC_DEFAULT, ESP_CLK_TREE_SRC_FREQ_PRECISION_APPROX, &i2c_sclk_freq));
+    #else
+    uint32_t i2c_sclk_freq = I2C_SCLK_FREQ;
+    #endif
+    int timeout = i2c_ll_calculate_timeout_us_to_reg_val(i2c_sclk_freq, self->timeout_us);
     i2c_set_timeout(self->port, (timeout > I2C_LL_MAX_TIMEOUT) ? I2C_LL_MAX_TIMEOUT : timeout);
     i2c_driver_install(self->port, I2C_MODE_MASTER, 0, 0, 0);
 }
```

For the second problem, include the `boards/sdkconfig.riscv` fragment in the `SDKCONFIG_DEFAULTS` list of files.

**Comment by dpgeorge** [comment]
Oh, and I think a dependencies lock file needs to be added for C5 as well.

**Comment by AZKKXL** [comment]
> Oh, and I think a dependencies lock file needs to be added for C5 as well.

Sorry, could we ask you to handle the maintenance of this after merging the PR later?

**Comment by dpgeorge** [comment]
OK, I've now added to this PR the following:
- fix I2C build on C5
- add dependencies lockfile for esp32c5
- add ESP32_GENERIC_C5 to the CI, to test that it builds

**Review by dpgeorge — APPROVED** [review]
