### PR TITLE
tools/ci: Fix typo of pipefail.

### PR DESCRIPTION
**Pull request by projectgus**
### Summary

Regression from typo in 449866cb0af3fc547df6538a6552517cc8974616 - PR #18033.

### CODE REVIEW

**Comment by projectgus** [comment]
Waiting to see if we get the same failure on the esp32 job, I couldn't see any likely cause for that one...

**Comment by projectgus** [comment]
I'm getting `AttributeError: 'NoneType' object has no attribute 'validation_alias'` locally now, I think this is an ESP-IDF Python package issue of some kind.

EDIT: Yes it is https://github.com/espressif/esp-idf/issues/17714

**Comment by projectgus** [comment]
I've posted a workaround for the esp32 build errors here:
https://github.com/espressif/esp-idf/issues/17714#issuecomment-3379844421

We could include the workaround in our CI, or we can wait for Espressif to release a component manager update that fixes it.

**Comment by jepler** [comment]
Thank you for fixing the problem I introduced.

**Comment by dpgeorge** [comment]
Looks like Espressif have fixed the IDF dependency issue.

**Comment by projectgus** [comment]
> Thank you for fixing the problem I introduced.

Typos are easy to fix, your PRs are doing much more important work! :grin:

**Review by dpgeorge — APPROVED** [review]
