### PR TITLE
zephyr: Link MicroPython with the Zephyr kernel library.

### PR DESCRIPTION
**Pull request by MaureenHelm**
Unlike most other Zephyr libraries, libkernel.a is not built as a whole-archive.

This change also fixes a linker error observed on nucleo_wb55rg while preparing an upgrade to Zephyr v3.5.0, caused by an undefined reference to `z_impl_k_busy_wait'.

Fixes the CI failure in #9335 
https://github.com/micropython/micropython/actions/runs/6671185807/job/18132599350?pr=9335

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thank you.  This looks independent to the current zephyr version, so can be merged now, without having to first resolve #9335.
