### PR TITLE
py/mkrules.mk: Add link to build troubleshooting on failure.

### PR DESCRIPTION
**Pull request by jimmo**
This is to help with the transition for https://github.com/micropython/micropython/pull/8813. It prints out a message with a link to [the wiki](https://github.com/micropython/micropython/wiki/Build-Troubleshooting) if the compile fails (see example below that is typical of what happens after #8813 with old type definitions).

I think this will be particularly useful for #8813 but hopefully will help address a whole class of issues that people run into (wrong IDF version, out of date submodules, etc).

I would like to implement this for CMake too, but figured I'd get feedback on the idea first before having to figure out how to do it in CMake.

```
machine_spi.c:154:6: error: 'mp_obj_type_t' {aka 'const struct _mp_obj_type_t'} has no member named 'locals_dict'
  154 |     .locals_dict = (mp_obj_dict_t *)&mp_machine_spi_locals_dict,
      |      ^~~~~~~~~~~
machine_spi.c:154:20: error: initialization of 'unsigned char' from 'mp_obj_dict_t *' {aka 'struct _mp_obj_dict_t *'} makes integer from pointer without a cast [-Werror=int-conversion]
  154 |     .locals_dict = (mp_obj_dict_t *)&mp_machine_spi_locals_dict,
      |                    ^
machine_spi.c:154:20: note: (near initialization for 'machine_hard_spi_type.slot_index_call')
machine_spi.c:154:20: error: initializer element is not computable at load time
machine_spi.c:154:20: note: (near initialization for 'machine_hard_spi_type.slot_index_call')
cc1: all warnings being treated as errors
See https://github.com/micropython/micropython/wiki/Build-Troubleshooting           <-------------------
make: *** [../../py/mkrules.mk:80: build-PYBV11/machine_spi.o] Error 1
```

_This work was funded through GitHub Sponsors._

### CODE REVIEW

**Comment by jimmo** [comment]
I realised that this was quite easy to do for the CMake builds if we do it in our wrapper Makefile, so added commits for rp2 and esp32.

File: py/mkrules.mk [hunk 1]
```diff
@@ -53,7 +53,7 @@ $(BUILD)/%.o: %.s
 
 define compile_c
 $(ECHO) "CC $<"
-$(Q)$(CC) $(CFLAGS) -c -MD -o $@ $<
+$(Q)$(CC) $(CFLAGS) -c -MD -o $@ $< || (echo -e "See \033[1;31mhttps://github.com/micropython/micropython/wiki/Build-Troubleshooting\033[0m" && false)
```
Comment (dpgeorge) [inline py/mkrules.mk:56]: is it worth making the string a (make) variable in this file, so it doesn't need to be repeated?

Comment (jimmo) [reply py/mkrules.mk]: Done

**Comment by dpgeorge** [comment]
Thank you!
