### PR TITLE
ESP32_S3: Fix build ESP32_GENERIC_S3.

### PR DESCRIPTION
**Pull request by hmaerki**
### Summary

Building `ESP32_GENERIC_S3` and `ESP32_GENERIC_S2` fails.

### Testing

`mpbuild build --idf v5.3.1 ESP32_GENERIC_S3` fails:
```
CMake Error at /opt/esp/idf/tools/cmake/build.cmake:544 (message):
  ERROR: Some components (espressif/tinyusb) in the "managed_components"
```

Tracking down the error leads to this command:
```
cd ports/esp32
GIT_SUBMODULES=$(idf.py -D MICROPY_BOARD=ESP32_GENERIC_S3 -D MICROPY_BOARD_DIR=".../ports/esp32/boards/ESP32_GENERIC_S3"  -B build-ESP32_GENERIC_S3/submodules -D ECHO_SUBMODULES=1 build
```
This commands errors with `Include directory '.../lib/tinyusb/src' is not a directory`.

### Fix

With this PR applied, these ports built successfully, eg. with return code 0:
```
set -euox pipefail

git clean -fxd; mpbuild build --idf v5.3.1 ARDUINO_NANO_ESP32 
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC 
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC D2WD
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC OTA
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC SPIRAM
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC UNICORE
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC_C3 
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC_C6 
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC_S2 
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC_S3 
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC FLASH_4M
git clean -fxd; mpbuild build --idf v5.3.1 ESP32_GENERIC SPIRAM_OCT
git clean -fxd; mpbuild build --idf v5.3.1 OLIMEX_ESP32_EVB 
git clean -fxd; mpbuild build --idf v5.3.1 OLIMEX_ESP32_POE 
```

## Notes

* How do your builds work?
* Builds using `--idf v5.2.2` failed as `pip list ... idf-component-manager 2.1.1` seems to be too old.
* Builds using `--idf v5.4` failed with
```
py/persistentcode.c:439:38: error: 'prelude_ptr' may be used uninitialized [-Werror=maybe-uninitialized]
```

### CODE REVIEW

**Comment by dpgeorge** [comment]
This could be a problem with `mpbuild`.  It's strange that there are three dots in the paths like:
```
MICROPY_BOARD_DIR=".../ports/esp32/boards/ESP32_GENERIC_S3"
```
where does that come from, is it really three dots?

Using IDF 5.2.2 everything works fine for me, eg:
```
$ make BOARD=ESP32_GENERIC_S2 submodules
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
make[1]: Entering directory 'micropython/ports/esp32'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Updating submodules: lib/berkeley-db-1.xx lib/tinyusb lib/micropython-lib
Synchronizing submodule url for 'lib/berkeley-db-1.xx'
Synchronizing submodule url for 'lib/micropython-lib'
Synchronizing submodule url for 'lib/tinyusb'
make[1]: Leaving directory 'micropython/ports/esp32'
```

**Comment by hmaerki** [comment]
> It's strange that there are three dots
That was my very long path which I manually stripped down.

> Using IDF 5.2.2 everything works fine for me, eg:
I was looking at the github docker container you use in the github action, it is 'ubuntu-20.04'.
This container installs the whole toolchain using './esp-idf/install.sh'.

However, in mpbuild we use the docker image [espressif/idf:v5.2.2](https://hub.docker.com/layers/espressif/idf/v5.2.2/images/sha256-06986a608a3f7609305e7e98bb71d51db0ded9bd0e25d6d4bb38bfab82d9c104). And this image seems to be a bit different from './esp-idf/install.sh'.

It would be great, if the 'official' espressif docker images would be supported. And this is what I tried to achieve with this MR.

If you prefer, I can create a new docker image for mpbuild based on https://github.com/micropython/micropython/blob/master/.github/workflows/ports_esp32.yml.

**Comment by hmaerki** [comment]
I found a nice solution.

Espressif hosts dockerfile here: https://github.com/espressif/esp-idf/tree/master/tools/docker.
This image works like a charm using `mpbuild` an Micropython.
The script to build the image is maintained in octoprobe-testbed_micropython and the image is hosted on docker hub.

So this MR became obsolete.

**Comment by mattytrentini** [comment]
I believe there is something unresolved going on with some combination of git, docker and perhaps WSL. And it may be due to synchronising submodules with newer/different versions of IDF - or git versions used in IDF. 

A similar error was reported in #16441 and I have been running into similar issues when changing between different IDF versions.

Sorry, not adding much here, just that I have observed some issues but I haven't yet put my finger on the root cause!

**Comment by dpgeorge** [comment]
> It would be great, if the 'official' espressif docker images would be supported. And this is what I tried to achieve with this MR.

I think this is a good goal, and I'm happy to make changes to achieve that goal.  I'm just not sure exactly what is wrong and why this PR fixes it...

**Comment by hmaerki** [comment]
@projectgus: Could you please ask espressif to rebuild docker image `espressif/idf:v5.2.2` and push again to docker hub.

Rationale: The image is outdated as `idf-component-manager` has undergone major changes.

```bash
docker run --rm -it espressif/idf:v5.2.2 pip list
idf-component-manager 1.5.2
```
However https://pypi.org/project/idf-component-manager/ is v2.1.1

**Comment by projectgus** [comment]
> @projectgus: Could you please ask espressif to rebuild docker image `espressif/idf:v5.2.2` and push again to docker hub.

@hmaerki I would approach this by opening an issue on the IDF repo: https://github.com/espressif/esp-idf/issues - so suggest you open the issue yourself as you're more familiar with the problem. If you don't get any response then let me know and I can poke someone behind the scenes, but hopefully won't be necessary.

**Comment by projectgus** [comment]
Alternatively, is it possible for us to change something in MicroPython so it builds with component manager v1.5.x and v2.x?
