### ISSUE TITLE
mpy_ld.py:  "AttributeError: 'Symbol' object has no attribute 'section'" when relocating data section

### ISSUE THREAD

**Issue by phlash** [micropython/micropython#8782]
While linking a larg(ish) project, with the latest micropython and ESP-IDF compiler, I had a failure in `mpy_ld.py` due to a relocation in a .data.rel.ro section that went via an unresolved (UND) symbol. The symbol was correctly resolved later on, however the logic in `do_relocation_data` does not take account of this fact, and fails when trying to de-reference the non-existant section attribute. Applying similar logic to that in `do_relocation_text` (see diff below) appears to fix this issue:
```diff
@@ -638,6 +639,9 @@ def do_relocation_data(env, text_addr, r):
         or env.arch.name == "EM_XTENSA"
         and r_info_type == R_XTENSA_32
     ):
+        # Bug fix: use resolved symbol if available (as per text relocs)
+        if hasattr(s, "resolved"):
+            s = s.resolved
         # Relocation in data.rel.ro to internal/external symbol
         if env.arch.word_size == 4:
```

**Comment by agatti** [comment]
A similar mechanism was introduced in 6760e00817ff6cb449134418411850fc577d0f9c when adding RV32 support.  Closing as complete.
