### ISSUE TITLE
Unable to build mpy-cross with Apple clang version 17.0.0

### ISSUE THREAD

**Issue by Anton-2** [micropython/micropython#18116]
### Port, board and/or hardware

any

### MicroPython version

Tested on v1.26.0 and latest master today v1.26.0-161-g8757eb715.

### Reproduction

cd mpy-cross
make

### Expected behaviour

Expected to build mpy-cross, like 

```
...
LINK build/mpy-cross
__TEXT	__DATA	__OBJC	others	dec	hex
425984	16384	0	4295032832	4295475200	10007c000
```

### Observed behaviour

Build fails with : 

```
CC ../py/parse.c
../py/parse.c:349:19: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]
  349 |                || mp_obj_is_float(*o)
      |                   ^~~~~~~~~~~~~~~~~~~
../py/obj.h:120:28: note: expanded from macro 'mp_obj_is_float'
  120 | #define mp_obj_is_float(o) mp_obj_is_type((o), &mp_type_float)
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../py/obj.h:979:31: note: expanded from macro 'mp_obj_is_type'
  979 | #define mp_obj_is_type(o, t) (mp_type_assert_not_bool_int_str_nonetype(t) && mp_obj_is_exact_type(o, t))
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../py/obj.h:973:5: note: expanded from macro 'mp_type_assert_not_bool_int_str_nonetype'
  973 |     MP_STATIC_ASSERT_NONCONSTEXPR((t) != &mp_type_bool), assert((t) != &mp_type_bool),         \
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../py/misc.h:76:45: note: expanded from macro 'MP_STATIC_ASSERT_NONCONSTEXPR'
   76 | #define MP_STATIC_ASSERT_NONCONSTEXPR(cond) MP_STATIC_ASSERT(cond)
      |                                             ^~~~~~~~~~~~~~~~~~~~~~
../py/misc.h:66:51: note: expanded from macro 'MP_STATIC_ASSERT'
   66 | #define MP_STATIC_ASSERT(cond) ((void)sizeof(char[1 - 2 * !(cond)]))
      |                                                   ^~~~~~~~~~~~~~~

... same error repeated ...

12 errors generated.
-e See https://github.com/micropython/micropython/wiki/Build-Troubleshooting
make: *** [build/py/parse.o] Error 1
```

### Additional Information

I was able to build may-cross before.

This fails after upgrading to macos 26, that probably upgraded clang to version 17.0.0 in the process.
This clang version seems to dislike the `MP_STATIC_ASSERT` macro.

Compilation works when silencing the `gnu-folding-constant` warning/error :

like (in micropython/py/misc.h) :
```c
// Static assertion macro
#define MP_STATIC_ASSERT(cond) \
    _Pragma("GCC diagnostic push") \
    _Pragma("GCC diagnostic ignored \"-Wgnu-folding-constant\"") \
    ((void)sizeof(char[1 - 2 * !(cond)])) \
    _Pragma("GCC diagnostic pop")
```

... but I don't know if its safe to do, and how it'll affect other compilers.

### Code of Conduct

Yes, I agree

**Comment by dpgeorge** [comment]
Thanks for the report.  Using clang version 20.1.8 locally on Arch Linux, I don't get any such warnings.  So it might due to Apple specific changes to clang, or clang 17 specifically doesn't like these expressions.

**Comment by bikeNomad** [comment]
I've been successfully using clang 17.0.0 on my Mac (`arm64-apple-darwin24.6.0`).
```
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Have you tried doing a clean first?
```
make -C mpy-cross clean
make -C mpy-cross
```

**Comment by projectgus** [comment]
I was able to reproduce the failure in #18129 by using GitHub's new macos-26 "public preview" runner in GitHub Actions. Will look to see if we can use `_Static_assert()` on compilers which support it.

@bikeNomad Not sure why you don't reproduce the same, that's odd.

**Comment by jepler** [comment]
> `../py/parse.c:892:68: error: variable length array folded to constant array as an extension [-Werror,-Wgnu-folding-constant]`


can we just `-Wno-gnu-folding-constant`? Over in #18145 I'm trying this.

**Comment by bikeNomad** [comment]
@projectgus I was able to build using clang 17.0.0 on my MacOS Sonoma system, but when I upgraded to Mac OS 26 Tahoe I get the same errors that @Anton-2 reported.

**Comment by dpgeorge** [comment]
Should be fixed by 33cf1ab3ccabecd156176ceebcd56332e8a5d325

**Comment by chiefenne** [comment]
I was trying to build [LVGL MicroPython binding](https://github.com/lvgl-micropython/lvgl_micropython) on MacOS Sequoia, Apple clang version 17.0.0 (clang-1700.3.19.1), Target: x86_64-apple-darwin24.6.0 and I got the same error. With the help of ChatGPT I could fix misc.h and sucessfull build:
LVGL (9.3.0) MicroPython (1.25.0) Binding compiled on 2025-10-19; Generic ESP32 module with ESP32

The suggested change in misc.h was:

```
/*
// Static assertion macro
define MP_STATIC_ASSERT(cond) ((void)sizeof(char[1 - 2 * !(cond)]))
*/

// -----------------------------------------------------------------------------
// Static assertion macros (portable across GCC, Clang, MSVC)
// -----------------------------------------------------------------------------

// Use C11 _Static_assert when available (Clang/GCC both support it)
#if defined(__clang__) || defined(__GNUC__) || \
    (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L)
    #define MP_STATIC_ASSERT(cond) _Static_assert(cond, "MP_STATIC_ASSERT failed")
#else
    // Fallback for pre-C11 compilers
    #define MP_STATIC_ASSERT(cond) \
        typedef char mp_static_assert_##__LINE__[(cond) ? 1 : -1]
#endif

// -----------------------------------------------------------------------------
// Some macros (like mp_obj_is_type) place these inside expressions.
// _Static_assert cannot appear there, so make this a no-op in such contexts.
// -----------------------------------------------------------------------------
#if !defined(MP_STATIC_ASSERT_NONCONSTEXPR)
    #define MP_STATIC_ASSERT_NONCONSTEXPR(cond) ((void)0)
#endif
```

That did the trick. Maybe that helps someone as an intermediate solution.

**Comment by dpgeorge** [comment]
This has been fixed in master, it's just not in a release yet.
